### PR TITLE
Fixes #3 - `in`, `remove`, and `get(key, defaultValue)` cannot be used with HashMaps that have not yet allocated memory

### LINKED ISSUE #3: `in`, `remove`, and `get(key, defaultValue)` cannot be used with HashMaps that have not yet allocated memory
```d
#!/usr/bin/env dub
/+dub.sdl:
dependency "dstruct" version="~>0.2.2"
+/
void main()
{
    import dstruct.map;
    HashMap!(int,int) emptyMap;
    assert(!(0 in emptyMap)); // crashes
    assert(!emptyMap.remove(0)); // crashes here if previous line is commented out
    assert(emptyMap.get(0, 404) == 404); // crashes here if previous two lines are commented out
}
```

### PR DESCRIPTION
**Pull request by n8sh**

### CODE REVIEW

**Review by w0rp — CHANGES_REQUESTED** [review]
Let's fix this instead with `@disable this();` so you are forced to construct the HashMap with a `minimumSize` specified. When the size is `0`, we should use `_bucketList = []`.

I expect the maps to be set up like so:

```d
auto map = HashMap!(int, string)(40)
```

**Comment by n8sh** [comment]
Doable but I want to double-check that this is what you want. Disabling default construction of `HashMap` will transitively disable default construction of `BasicGraph` which is the style used in every unit test in `dstruct.graph`.

**Comment by w0rp** [comment]
> Doable but I want to double-check that this is what you want. Disabling default construction of `HashMap` will transitively disable default construction of `BasicGraph` which is the style used in every unit test in `dstruct.graph`.

Oh. That's a very good point. This is probably about as good as it gets then.

**Comment by w0rp** [comment]
As I say when maintaining ALE: Cheers! :beers:

**Pull request merged**
